#========================================server config=====================================
server:
  port: 8080
#========================================spring config=====================================
spring:
  application:
    name: seata-springcloud-web
  devtools:
    restart:
      enabled: false
#========================================feign config=====================================
feign:
  hystrix:
    enabled: true
ribbon:
  ReadTimeout: 30000 #处理超时时间 默认5秒
  ConnectTimeout: 10000 #连接超时时间 默认2秒

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000 #断路切换超时
#========================================eureka config=====================================
eureka:
  client:
    serviceUrl:
      defaultZone: http://@localhost:8761/eureka/


